// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication1.Models.DEPARTMENT", b =>
                {
                    b.Property<int>("DEPARTMENT_CODE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DEPARTMENT_CODE")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DEPARTMENT_CODE"), 1L, 1);

                    b.Property<string>("DEPARTMENT_NAME_ENG")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DEPARTMENT_NAME_ENG")
                        .HasColumnOrder(3);

                    b.Property<string>("DEPARTMENT_NAME_THA")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DEPARTMENT_NAME_THA")
                        .HasColumnOrder(2);

                    b.HasKey("DEPARTMENT_CODE");

                    b.ToTable("DEPARTMENT");
                });

            modelBuilder.Entity("WebApplication1.Models.EMPLOYEE", b =>
                {
                    b.Property<int>("EMPLOYEE_CODE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EMPLOYEE_CODE")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EMPLOYEE_CODE"), 1L, 1);

                    b.Property<DateTime>("BIRTH_DATE")
                        .HasColumnType("DATETIME")
                        .HasColumnName("BIRTH_DATE")
                        .HasColumnOrder(8);

                    b.Property<string>("BLOOD_TYPE")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("BLOOD_TYPE")
                        .HasColumnOrder(12);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EMAIL")
                        .HasColumnOrder(14);

                    b.Property<string>("FIRST_NAME_ENG")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FIRST_NAME_ENG")
                        .HasColumnOrder(4);

                    b.Property<string>("FIRST_NAME_THA")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FIRST_NAME_THA")
                        .HasColumnOrder(2);

                    b.Property<string>("GENDER")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("GENDER")
                        .HasColumnOrder(7);

                    b.Property<string>("LAST_NAME_ENG")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("LAST_NAME_ENG")
                        .HasColumnOrder(5);

                    b.Property<string>("LAST_NAME_THA")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("LAST_NAME_THA")
                        .HasColumnOrder(3);

                    b.Property<string>("NATIONALITY_ID")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("NATIONALITY_ID")
                        .HasColumnOrder(9);

                    b.Property<string>("NICKNAME")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("NICKNAME")
                        .HasColumnOrder(6);

                    b.Property<string>("PHONE_EMPLOYEE")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("PHONE_EMPLOYEE")
                        .HasColumnOrder(13);

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<string>("RACE_ID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("RACE_ID")
                        .HasColumnOrder(10);

                    b.Property<string>("RELIGION")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("RELIGION")
                        .HasColumnOrder(11);

                    b.HasKey("EMPLOYEE_CODE");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.ToTable("EMPLOYEE");
                });

            modelBuilder.Entity("WebApplication1.Models.POSITION", b =>
                {
                    b.Property<int>("POSITION_CODE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("POSITION_CODE")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("POSITION_CODE"), 1L, 1);

                    b.Property<string>("POSITION_NAME_ENG")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("POSITION_NAME_ENG")
                        .HasColumnOrder(3);

                    b.Property<string>("POSITION_NAME_THA")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("POSITION_NAME_THA")
                        .HasColumnOrder(2);

                    b.HasKey("POSITION_CODE");

                    b.ToTable("POSITION");
                });

            modelBuilder.Entity("WebApplication1.Models.EMPLOYEE", b =>
                {
                    b.HasOne("WebApplication1.Models.DEPARTMENT", null)
                        .WithMany("EMPLOYEEs")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.POSITION", "POSITION")
                        .WithMany("EMPLOYEEs")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("POSITION");
                });

            modelBuilder.Entity("WebApplication1.Models.DEPARTMENT", b =>
                {
                    b.Navigation("EMPLOYEEs");
                });

            modelBuilder.Entity("WebApplication1.Models.POSITION", b =>
                {
                    b.Navigation("EMPLOYEEs");
                });
#pragma warning restore 612, 618
        }
    }
}
